# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import os
from pathlib import Path

import toml

current_directory = Path(os.path.dirname(__file__))
# : add if else for that  root_project_directory = "../"
root_project_directory = "../"

pyproject_file: Path = root_project_directory + "pyproject.toml"

pyproject_version = toml.load(pyproject_file)["tool"]["poetry"]["version"]
# : make it all authors nicely
pyproject_authors = str(toml.load(pyproject_file)["tool"]["poetry"]["authors"][0])

# -- Project information -----------------------------------------------------

project = "{{ cookiecutter.project_slug }}"
# : Template that in the cookiecutter tempalte
copyright = f"{% now 'local', '%Y' %}, {pyproject_authors}"
author = pyproject_authors

# The short X.Y version
version = pyproject_version

# The full version, including alpha/beta/rc tags
release = pyproject_version


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.githubpages",
    "sphinx_rtd_theme",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# Use the Read the docs theme
html_theme = "sphinx_rtd_theme"
# Material theme options (see theme.conf for more information)

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Extension configuration -------------------------------------------------
