{% raw %}
name: 📄 Build docs
on:
    pull_request:
    push:
        branches: ["main", "develop", "release"]

jobs:
    lint:
        strategy:
          matrix:
            python-version: ["3.10"]
        name: 📄 Build docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Python ${{ matrix.python-version }}
            - uses: actions/setup-python@v4
              with:
                python-version: "${{ matrix.python-version }}" 
            - name: Install and configure Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.2
                virtualenvs-create: true
                virtualenvs-in-project: false
                installer-parallel: true
            - name: Run tests
              run: tox -e doc

{% endraw %}