{% raw %}
name: 🔨 Install dependencies
on:
    pull_request:

jobs:
    cinstall:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.9", "3.10", "3.11"]
        name: 🔨 Install dependencies
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            - name: Install Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"
            - name: Check installation procedure
              run: |
                  pip install tox poetry
                  tox -e install

{% endraw %}