{% raw %}
name: 📦 Package
on:
    pull_request:

jobs:
    package:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.9", "3.10", "3.11"]
        name: 📦 Run package checks
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            - name: Install Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              id: cache
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "pip"
            - name: Restore dependencies
              id: tox
              uses: actions/cache/restore@v3
              with:
                path: |
                  .tox
                key: ${{ runner.os }}-${{ matrix.python-version }}-tox-package
            - name: Check package build
              run: |
                  pip install tox poetry
                  tox -e build
            - name: Save dependencies
              id: tox-save
              uses: actions/cache/save@v3
              with:
                path: |
                  .tox
                key: ${{ runner.os }}-${{ matrix.python-version }}-tox-package

{% endraw %}