{% raw %}
name: 📦 Package
on:
    pull_request:

jobs:
    package:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.9", "3.10", "3.11"]
        name: 📦 Run package checks
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            - name: Install Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"
            - name: Check package build
              run: |
                  pip install tox poetry
                  tox -e build

{% endraw %}